# Generated by Django 6.0 on 2026-02-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='provider',
            field=models.CharField(blank=True, choices=[('netflix', 'Netflix'), ('prime', 'Amazon Prime Video'), ('apple', 'Apple TV')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
